var newKeyboard = [{
  'letter': 'tab',
  'keyCode': 9,
  'width': '72',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'q',
  'keyCode': 81,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'w',
  'keyCode': 87,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'e',
  'keyCode': 69,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'r',
  'keyCode': 82,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 't',
  'keyCode': 84,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'y',
  'keyCode': 89,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'u',
  'keyCode': 85,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'i',
  'keyCode': 73,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'o',
  'keyCode': 79,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'p',
  'keyCode': 80,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': '[',
  'keyCode': 219,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': ']',
  'keyCode': 221,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'Backspace',
  'keyCode': 221,
  'width': '85',
  'height': '34',
  'lastInRow': true
}, {
  'letter': 'Caps Lock',
  'keyCode': 20,
  'width': '90',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'a',
  'keyCode': 65,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 's',
  'keyCode': 83,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'd',
  'keyCode': 68,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'f',
  'keyCode': 70,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'g',
  'keyCode': 71,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'h',
  'keyCode': 72,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'j',
  'keyCode': 74,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'k',
  'keyCode': 75,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'l',
  'keyCode': 76,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': ';',
  'keyCode': 186,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': "'",
  'keyCode': 222,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': "Enter",
  'keyCode': 13,
  'width': '105',
  'height': '34',
  'lastInRow': true
}, {
  'letter': 'Shift',
  'keyCode': 16,
  'width': '100',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'z',
  'keyCode': 90,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'x',
  'keyCode': 88,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'c',
  'keyCode': 67,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'v',
  'keyCode': 86,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'b',
  'keyCode': 66,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'n',
  'keyCode': 78,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'm',
  'keyCode': 77,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': ',',
  'keyCode': 188,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': '.',
  'keyCode': 190,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': '/',
  'keyCode': 191,
  'width': '34',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'Shift',
  'keyCode': 16,
  'width': '90',
  'height': '34',
  'lastInRow': true
}, {
  'letter': 'Ctrl',
  'keyCode': 16,
  'width': '45',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'Win',
  'keyCode': 16,
  'width': '45',
  'height': '34',
  'lastInRow': false
}, {
  'letter': 'Alt',
  'keyCode': 16,
  'width': '45',
  'height': '34',
  'lastInRow': false
}, {
  'letter': '',
  'keyCode': 32,
  'width': '190',
  'height': '34',
  'lastInRow': true
}]
